apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onlyapi.fullname" . }}-config
  labels:
    {{- include "onlyapi.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  DATABASE_DRIVER: {{ .Values.config.databaseDriver | quote }}
  REDIS_ENABLED: {{ .Values.config.redisEnabled | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  RATE_LIMIT_WINDOW_MS: {{ .Values.config.rateLimitWindowMs | quote }}
  RATE_LIMIT_MAX: {{ .Values.config.rateLimitMax | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  I18N_DEFAULT_LOCALE: {{ .Values.config.i18nDefaultLocale | quote }}
  I18N_SUPPORTED_LOCALES: {{ .Values.config.i18nSupportedLocales | quote }}
