apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onlyapi.fullname" . }}-secrets
  labels:
    {{- include "onlyapi.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
